export interface ICollectionInput {
	name: string,
	color: string,
	profile: string
}

export interface IChangeCollectionLockInput {
	isLocked: boolean
}

export interface ICollectionMeta {
	phrasesCount: number,
	repetitionsCount: number,
	lastRepetition: number | null
}

export interface ICollection {
	id: string,
	name: string,
	isLocked: boolean,
	isAutoGenerated: boolean,
	color: string,
	created: number,
	lastUpdate: number,
	profile: string,
	meta: ICollectionMeta,
	phrases: String[],
	repetitions: String[]
}