import { useEffect, useState } from "react";
import { Alert, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery } from "@apollo/client";
import { CHANGE_COLLECTION_LOCK, DELETE_COLLECTION, GET_COLLECTION, GET_PROFILE_COLLECTIONS, GET_PROFILE_COLLECTIONS_FOR_PHRASES } from "../../../query/collections";
import EditCollection from "../../../components/EditCollection";
import { fontColor } from "@styles/variables";
import { useClickOutside } from "react-native-click-outside";
import ModalComponent from "@components/ModalComponent";
import { observer } from "mobx-react-lite";
import errorMessage from "@store/toastMessage";
import loadingSpinner from "@store/loadingSpinner";
import { StackScreenProps } from "@react-navigation/stack";
import { StackNavigatorParams } from "../Collections";
import ModalWithBody from "@components/ModalWithBody";

type TProps = StackScreenProps<StackNavigatorParams, "Collection", "collectionsNavigator">;

const CollectionHeaderButtons = observer(function({ route, navigation }: TProps) {
	const colId = route.params.colId;
	const { data, refetch } = useQuery(GET_COLLECTION, { variables: { id: colId } });
	const [ displayModal, setDisplayModal ] = useState(false);
	const [ deleteCollection ] = useMutation(DELETE_COLLECTION);
	const [ changeCollectionLock ] = useMutation(CHANGE_COLLECTION_LOCK);
	const [ displayMenu, setDisplayMenu ] = useState(false);
	const ref = useClickOutside(() => setDisplayMenu(false));

	useEffect(() => {
		if(!data) return;

		navigation.setOptions({
			headerStyle: {
				backgroundColor: data.getCollection.color
			},
			headerTintColor: "white"
		})
	}, [data])

	if(!data) return null;

	function deleteHandler() {
		Alert.alert(`Delete collection "${data.getCollection.name}" ?`, "The collection will be deleted with all it's phrases", [
			{
				text: "Cancel",
				style: "cancel"
			},
			{
				text: "Delete",
				style: "destructive",
				onPress: async () => {
					loadingSpinner.setLoading();

					try {
						await deleteCollection({
							variables: { id: colId },
							update: (cache) => {
								cache.evict({ id: `Collection:${colId}` })
							}
						});
					} catch (e: any) {
						console.log(e);
						errorMessage.setErrorMessage(`Failed to delete collection ${e.toString()}`)
					}

					loadingSpinner.dismissLoading();
					navigation.navigate("Collections");
				}
			}
		])
	}

	async function setLockHandler() {
		loadingSpinner.setLoading();

		try {
			await changeCollectionLock({
				variables: { 
					id: colId,
					input: {
						isLocked: !data.getCollection.isLocked
					}
				}
			});
		} catch (e: any) {
			console.log(e);
			errorMessage.setErrorMessage(`Failed to set collection lock ${e.toString()}`)
		}

		await refetch();
		loadingSpinner.dismissLoading();
	}

	if(data.getCollection.isAutoGenerated) return null;

	return (
		<View style={styles.container}>
			<ModalWithBody visible={displayModal} onClose={() => setDisplayModal(false)}>
				<EditCollection mutateId={data.getCollection.id} onReady={() => setDisplayModal(false)} />
			</ModalWithBody>
			<TouchableOpacity
				activeOpacity={0.75}
				onPress={() => setDisplayMenu(true)}
				style={styles.menuContainer}
			>
				<Ionicons name="ellipsis-vertical" size={24} color="#eee" />
				{
					displayMenu &&
					<View style={styles.menuBody} ref={ref}>
						<TouchableOpacity
							activeOpacity={0.5}
							onPress={setLockHandler}
							style={styles.menuItem}
						>
							<Text style={styles.menuItemText}>
								{data.getCollection.isLocked ? "Unlock" : "Lock"}
							</Text>
							<Ionicons name={data.getCollection.isLocked ? "lock-open" : "lock-closed"} size={21} color="gray" />
						</TouchableOpacity>
						<TouchableOpacity
							activeOpacity={0.5}
							onPress={() => {
								setDisplayModal(true);
								setDisplayMenu(false);
							}}
							style={styles.menuItem}
						>
							<Text style={styles.menuItemText}>
								Edit
							</Text>
							<Ionicons name="pencil" size={21} color="gray" />
						</TouchableOpacity>
						<TouchableOpacity
							activeOpacity={0.5}
							onPress={deleteHandler}
							style={styles.menuItem}
						>
							<Text style={styles.menuItemText}>
								Delete
							</Text>
							<Ionicons name="trash-outline" size={21} color="gray" />
						</TouchableOpacity>
					</View>
				}
			</TouchableOpacity>
		</View>
	)
});

const styles = StyleSheet.create({
	container: {
		flexDirection: "row",
		gap: 15,
		paddingHorizontal: 15,
		alignItems: "center"
	},
	menuContainer: {
		position: "relative"
	},
	menuBody : {
		position: "absolute",
		top: 0,
		right: 0,
		width: 160,
		padding: 12,
		borderRadius: 4,
		gap: 11,
		backgroundColor: "white"
	},
	menuItem: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
		justifyContent: "space-between"
	},
	menuItemText: {
		fontSize: 16,
		color: fontColor
	}
})

export default CollectionHeaderButtons;