export interface ICollectionMeta {
	phrasesCount: number,
	repetitionsCount: number,
	lastRepetition: number | null
}

export interface IAutoGeneratedCollectionMeta {
	type: "auto" | "htm" | "interval"
}

export interface ICollection {
	id: string,
	name: string,
	isLocked: boolean,
	isAutoGenerated: boolean,
	color: string,
	created: number,
	lastUpdate: number,
	profile: string,
	meta: ICollectionMeta,
	autoGeneratedCollectionMeta: IAutoGeneratedCollectionMeta | null,
	phrases: string[],
	repetitions: string[],
	userId: string
}

export type TCollectionNameId = Pick<ICollection, "name" | "id">