import { gql } from "@apollo/client";

export const GET_COLLECTION = gql`
	query getCollection($id: ID!) {
		getCollection(id: $id) {
			id,
			name,
			isLocked,
			isAutoGenerated,
			color
		}
	}
`;

export const GET_PROFILE_COLLECTIONS = gql`
	query getProfileCollections($id: ID!) {
		getProfileCollections(id: $id) {
			id,
			name,
			lastUpdate,
			isLocked,
			color,
			meta {
				phrasesCount
			}
		}
	}
`;

export const GET_PROFILE_COLLECTIONS_FOR_PHRASES = gql`
	query getProfileCollections($id: ID!) {
		getProfileCollections(id: $id) {
			id,
			name,
			isLocked
		}
	}
`;


export const GET_COLLECTION_NAMEID = gql`
	query getCollection($id: ID!) {
		getCollection(id: $id) {
			id,
			name
		}
	}
`;

export const GET_COLLECTION_META = gql`
	query getCollection($id: ID!) {
		getCollection(id: $id) {
			id,
			name,
			meta {
				phrasesCount,
				repetitionsCount,
				lastRepetition
			}
		}
	}
`;

export const CREATE_COLLECTION = gql`
	mutation createCollection($input: CollectionInput!) {
		createCollection(input: $input) {
			id,
			name,
			lastUpdate,
			isLocked,
			color,
			meta {
				phrasesCount
			}
		}
	}
`;

export const MUTATE_COLLECTION = gql`
	mutation mutateCollection($id: ID!, $input: MutateCollectionInput!) {
		mutateCollection(id: $id, input: $input)  {
			id,
			name,
			color
		}
	}
`;

export const MUTATE_COLLECTION_META = gql`
	mutation mutateCollectionMeta($id: ID!, $input: CollectionMetaInput!) {
		mutateCollectionMeta(id: $id, input: $input)
	}
`;

export const CHANGE_COLLECTION_LOCK = gql`
	mutation changeCollectionLock($id: ID!, $input: ChangeCollectionLockInput!) {
		changeCollectionLock(id: $id, input: $input)
	}
`;


export const DELETE_COLLECTION = gql`
	mutation deleteCollection($id: ID!) {
		deleteCollection(id: $id) 
	}
`;

export const GENERATE_AUTO_COLLECTION = gql`
	mutation generateAutoCollection($type: String!) {
		generateAutoCollection(type: $type) {
			id,
			name,
			lastUpdate,
			isLocked,
			isAutoGenerated,
			color,
			created,
			repetitions,
			profile,
			meta {
				phrasesCount,
				repetitionsCount,
				lastRepetition
			}
		}
	}
`;