import { ICollection } from "../types/collections";

const generateId = require("../utils/generateId");

export class Collection implements Omit<ICollection, "isAutoGenerated"> {
	id = generateId();
	isLocked = false;
	created = new Date().getTime();
	lastUpdate = new Date().getTime();
	meta = {
		phrasesCount: 0,
		repetitionsCount: 0,
		lastRepetition: null
	};
	phrases = [];
	repetitions = [];

	name: string;
	color: string;
	profile: string;

	constructor(name: string, color: string, profile: string) {
		this.name = name;
		this.color = color;
		this.profile = profile
	}
}