import { ICollectionInput } from "@ts-backend/collections";
import { ICollection } from "../../../types/collections";

import generateId from "../misc/generateId";

export class Collection implements Omit<ICollection, "isAutoGenerated" | "autoGeneratedCollectionMeta"> {
	id = generateId();
	isLocked = false;
	meta = {
		phrasesCount: 0,
		repetitionsCount: 0,
		lastRepetition: null
	};
	phrases = [];
	repetitions = [];

	name: string;
	color: string;
	profile: string;
	userId: string;
	created: number;
	lastUpdate: number;

	constructor(input: ICollectionInput, userId: string) {
		const timestamp = new Date().getTime();
		
		this.name = input.name;
		this.color = input.color;
		this.profile = input.profile,
		this.userId = userId
		this.created = timestamp;
		this.lastUpdate = timestamp;
	}
}